project:
  type: website

website:
  title: "2025 Survival Survey Dashboard"
  navbar:
    left:
      - href: survival.qmd  # Make this the first item
        text: Home
      # Other navbar items...