on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 20 * * *'  # Daily at 23:00 East Africa time
    
name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
# Install R first
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5'  # Specify your required R version

      # Install required R packages
      - name: Install R dependencies
        run: |
          R -e "install.packages(c('dplyr', 'tidyr', 'plotly', 'stringr'), repos = 'https://cloud.r-project.org')"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}